# Generated by Django 2.2 on 2019-12-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='slug_name',
            field=models.CharField(default='slug_name', max_length=50),
        ),
    ]
