# Generated by Django 2.2 on 2019-12-29 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20191227_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales.Local', verbose_name='Local'),
        ),
    ]
